# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - pwd
    - ls ./public
    - GIT_COMMIT_VERSION=$(git rev-parse HEAD)
    - GIT_COMMIT_TAG=$(git describe --tags)
    - cp ./build/proquestDLLSetup.msi ./public/proquestDLLSetup-latest.msi
    - cp ./build/proquestDLLSetup.msi ./public/proquestDLLSetup-${GIT_COMMIT_VERSION}.msi
    - cp ./build.TS/airQuestTSSetup.msi ./public/airQuestTSSetup-latest.msi
    - cp ./build.TS/airQuestTSSetup.msi ./public/airQuestTSSetup-${CI_COMMIT_VERSION}.msi
    - cp ./build/proquestDLLSetup.msi ./public/proquestDLLSetup-${GIT_COMMIT_TAG}.msi
    - cp ./build.TS/airQuestTSSetup.msi ./public/airQuestTSSetup-${GIT_COMMIT_TAG}.msi
    - echo commit ${GIT_COMMIT_VERSION} > ./public/version.txt
    - echo tag ${GIT_COMMIT_TAG} >> ./public/version.txt
    - ls ./public >>./public/version.txt

  artifacts:
    paths:
      - public

  only:
    - master

pages_tags: 
  stage: deploy
  script:
    - pwd
    - ls ./public
    - GIT_COMMIT_VERSION=$(git rev-parse HEAD)
    - cp ./build/proquestDLLSetup.msi ./public/proquestDLLSetup-latest.msi
    - cp ./build/proquestDLLSetup.msi ./public/proquestDLLSetup-${GIT_COMMIT_VERSION}.msi
    - cp ./build.TS/airQuestTSSetup.msi ./public/airQuestTSSetup-latest.msi
    - cp ./build.TS/airQuestTSSetup.msi ./public/airQuestTSSetup-${CI_COMMIT_VERSION}.msi
    - cp ./build/proquestDLLSetup.msi ./public/proquestDLLSetup-${CI_COMMIT_TAG}.msi
    - cp ./build.TS/airQuestTSSetup.msi ./public/airQuestTSSetup-${CI_COMMIT_TAG}.msi
    - echo commit ${GIT_COMMIT_VERSION} > ./public/version.txt
    - echo tag ${CI_COMMIT_TAG} >> ./public/version.txt
    - cp ./3rdparty/VFP9SP2RT.exe ./public/VFP9SP2RT.exe
    - ls ./public >> ./public/version.txt

  artifacts:
    paths:
      - public

  only:
    - tags
